openapi: 3.0.3
info:
  title: Invoice Payment API
  description: API to handle invoice payments with card details
  version: 1.0.0

paths:
  /api/payment:
    post:
      summary: Process a payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        '200':
          description: Payment Success!
        '400':
          description: Bad request (invoice is required)
  /api/webhook:
    post:
      summary: Save a webhook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WebhookRequest"
      responses:
        '200':
          description: Webhook created successfully!
        '409':
          description: Conflict - webhook already exists

components:
  schemas:
    PaymentRequest:
      type: object
      required:
        - email
        - cvc
        - expiryDate
        - cardHolderName
        - zipCode
        - cardNumber
        - invoices
        - amount
        - refNumber
      properties:
        email:
          type: string
          format: email
        cardNumber:
          type: string
